In [15]:
import numpy as np
import pandas as pd
#help(pd.Series)

In [54]:
myIndex = ['USA','MEXICO','CANADA','NIGERIA']
myData = [1776,1821,1867,1960]
ser = pd.Series(index = myIndex,data = myData)
ser

USA        1776
MEXICO     1821
CANADA     1867
NIGERIA    1960
dtype: int64

In [48]:
Grade = ['A','A','A','A','A','C','C','A','A']
Course = ['MCEN312','MATHS342','MCEN304','MCEN302','COSC344','MCEN310','MCEN306','MCEN308','ATEN304']
SER  = pd.Series(index = Course,data = Grade)
SER

MCEN312     A
MATHS342    A
MCEN304     A
MCEN302     A
COSC344     A
MCEN310     C
MCEN306     C
MCEN308     A
ATEN304     A
dtype: object

In [45]:
mydict = {'faisal': '300L','fatima':'200L','maryam':'SS3','sakina':'SS2'}
my=pd.Series(mydict)my
my

SyntaxError: invalid syntax (4045990279.py, line 2)

In [81]:
q1 = {'Chaina':2992,'Nigeria':2833,'Usa':2221,'Japan':1000}
q2 = {'Usa':1344,'Chaina':2984,'Sudia':1888,'Nigeria':2984}
sales_q1 = pd.Series(q1)
sales_q2 = pd.Series(q2)
sales_q1

Chaina     2992
Nigeria    2833
Usa        2221
Japan      1000
dtype: int64

In [70]:
sales_q2

India     1344
Qatar     2984
Saudi     1888
Taiwan    2984
dtype: int64

In [79]:

sales_q1.keys()

Index(['Chaina', 'Nigeria', 'Usa', 'Japan'], dtype='object')

In [82]:
sales_q2.keys()

Index(['Usa', 'Chaina', 'Sudia', 'Nigeria'], dtype='object')

In [89]:
sales_q1 + 4000

Chaina     6992
Nigeria    6833
Usa        6221
Japan      5000
dtype: int64

In [91]:
sales_q1 + sales_q2

Chaina     5976.0
Japan         NaN
Nigeria    5817.0
Sudia         NaN
Usa        3565.0
dtype: float64

sales_q1.add(sales_q2,fill_value = 0)

DATAFRAME:::

In [110]:
from numpy import random
import pandas as pd

In [150]:
np.random.seed(101)
fd = random.randint(0,101,(4,3))
Index = ['CA','NY','AZ','TX']
columns= ['Jan','Feb','Match']
df =pd.DataFrame(fd,Index,columns)
df


Jan  Feb  Match
CA   95   11     81
NY   70   63     87
AZ   75    9     77
TX   40    4     63

In [152]:
pwd

'C:\\Users\\FAISAL\\faisal-ai-mechatronics'

In [154]:
ls

 Volume in drive C has no label.
 Volume Serial Number is B450-AEEF

 Directory of C:\Users\FAISAL\faisal-ai-mechatronics

10/21/2025  02:38 PM    <DIR>          .
10/21/2025  06:01 AM    <DIR>          ..
10/21/2025  06:06 AM    <DIR>          .ipynb_checkpoints
10/16/2025  05:22 PM                 0 day1_python_basics.ipynb
10/21/2025  02:27 PM             8,640 day-12_pandas.ipynb
07/05/2020  01:39 AM                51 example.csv
10/16/2025  05:22 PM                35 hello.py
07/12/2020  08:41 PM        25,112,317 hotel_booking_data.csv
02/07/2020  08:26 PM               177 movie_scores.csv
07/01/2020  11:56 PM            17,727 mpg.csv
07/05/2020  02:10 AM                51 new_file.csv
09/26/2020  01:16 AM                51 newfile.csv
10/16/2025  05:22 PM               100 README.md
07/07/2020  01:10 AM             1,320 Sales_Funnel_CRM.csv
01/27/2020  10:28 PM            18,752 tips.csv
10/21/2025  05:59 AM    <DIR>          Untitled Folder
              12 File(s)     25,15

In [20]:
import numpy as np
import pandas as pd
df = pd.read_csv('C:\\Users\\FAISAL\\faisal-ai-mechatronics\\tips.csv')
df

total_bill   tip     sex smoker   day    time  size  price_per_person  \
0         16.99  1.01  Female     No   Sun  Dinner     2              8.49   
1         10.34  1.66    Male     No   Sun  Dinner     3              3.45   
2         21.01  3.50    Male     No   Sun  Dinner     3              7.00   
3         23.68  3.31    Male     No   Sun  Dinner     2             11.84   
4         24.59  3.61  Female     No   Sun  Dinner     4              6.15   
..          ...   ...     ...    ...   ...     ...   ...               ...   
239       29.03  5.92    Male     No   Sat  Dinner     3              9.68   
240       27.18  2.00  Female    Yes   Sat  Dinner     2             13.59   
241       22.67  2.00    Male    Yes   Sat  Dinner     2             11.34   
242       17.82  1.75    Male     No   Sat  Dinner     2              8.91   
243       18.78  3.00  Female     No  Thur  Dinner     2              9.39   

             Payer Name         CC Number Payment ID  
0    Christy Cunningham  3560325168603410    Sun2959  
1        Douglas Tucker  4478071379779230    Sun4608  
2        Travis Walters  6011812112971322    Sun4458  
3      Nathaniel Harris  4676137647685994    Sun5260  
4          Tonya Carter  4832732618637221    Sun2251  
..                  ...               ...        ...  
239       Michael Avila  5296068606052842    Sat2657  
240      Monica Sanders  3506806155565404    Sat1766  
241          Keith Wong  6011891618747196    Sat3880  
242        Dennis Dixon     4375220550950      Sat17  
243     Michelle Hardin  3511451626698139    Thur672  

[244 rows x 11 columns]

In [163]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size',
       'price_per_person', 'Payer Name', 'CC Number', 'Payment ID'],
      dtype='object')

In [170]:
df.head(4)

total_bill   tip     sex smoker  day    time  size  price_per_person  \
0       16.99  1.01  Female     No  Sun  Dinner     2              8.49   
1       10.34  1.66    Male     No  Sun  Dinner     3              3.45   
2       21.01  3.50    Male     No  Sun  Dinner     3              7.00   
3       23.68  3.31    Male     No  Sun  Dinner     2             11.84   

           Payer Name         CC Number Payment ID  
0  Christy Cunningham  3560325168603410    Sun2959  
1      Douglas Tucker  4478071379779230    Sun4608  
2      Travis Walters  6011812112971322    Sun4458  
3    Nathaniel Harris  4676137647685994    Sun5260

In [167]:
df.tail(4)

total_bill   tip     sex smoker   day    time  size  price_per_person  \
240       27.18  2.00  Female    Yes   Sat  Dinner     2             13.59   
241       22.67  2.00    Male    Yes   Sat  Dinner     2             11.34   
242       17.82  1.75    Male     No   Sat  Dinner     2              8.91   
243       18.78  3.00  Female     No  Thur  Dinner     2              9.39   

          Payer Name         CC Number Payment ID  
240   Monica Sanders  3506806155565404    Sat1766  
241       Keith Wong  6011891618747196    Sat3880  
242     Dennis Dixon     4375220550950      Sat17  
243  Michelle Hardin  3511451626698139    Thur672

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   total_bill        244 non-null    float64
 1   tip               244 non-null    float64
 2   sex               244 non-null    object 
 3   smoker            244 non-null    object 
 4   day               244 non-null    object 
 5   time              244 non-null    object 
 6   size              244 non-null    int64  
 7   price_per_person  244 non-null    float64
 8   Payer Name        244 non-null    object 
 9   CC Number         244 non-null    int64  
 10  Payment ID        244 non-null    object 
dtypes: float64(3), int64(2), object(6)
memory usage: 21.1+ KB


In [23]:
df.describe()

total_bill         tip        size  price_per_person     CC Number
count  244.000000  244.000000  244.000000        244.000000  2.440000e+02
mean    19.785943    2.998279    2.569672          7.888197  2.563496e+15
std      8.902412    1.383638    0.951100          2.914234  2.369340e+15
min      3.070000    1.000000    1.000000          2.880000  6.040679e+10
25%     13.347500    2.000000    2.000000          5.800000  3.040731e+13
50%     17.795000    2.900000    2.000000          7.255000  3.525318e+15
75%     24.127500    3.562500    3.000000          9.390000  4.553675e+15
max     50.810000   10.000000    6.000000         20.270000  6.596454e+15

In [175]:
len(df)

244

In [25]:
df.describe().transpose()

count          mean           std           min  \
total_bill        244.0  1.978594e+01  8.902412e+00  3.070000e+00   
tip               244.0  2.998279e+00  1.383638e+00  1.000000e+00   
size              244.0  2.569672e+00  9.510998e-01  1.000000e+00   
price_per_person  244.0  7.888197e+00  2.914234e+00  2.880000e+00   
CC Number         244.0  2.563496e+15  2.369340e+15  6.040679e+10   

                           25%           50%           75%           max  
total_bill        1.334750e+01  1.779500e+01  2.412750e+01  5.081000e+01  
tip               2.000000e+00  2.900000e+00  3.562500e+00  1.000000e+01  
size              2.000000e+00  2.000000e+00  3.000000e+00  6.000000e+00  
price_per_person  5.800000e+00  7.255000e+00  9.390000e+00  2.027000e+01  
CC Number         3.040731e+13  3.525318e+15  4.553675e+15  6.596454e+15

In [36]:
numbers =np.array(range(1,31))
print(numbers)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]


In [40]:
new = np.reshape(numbers,(5,6))
print(new)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]


In [43]:
columns = ['MON','TUE','WED','THUR','FRI','SAT']
INDEX = ['R1','R2','R3','R4','R5']
df =pd.DataFrame(new,INDEX,columns)
df

MON  TUE  WED  THUR  FRI  SAT
R1    1    2    3     4    5    6
R2    7    8    9    10   11   12
R3   13   14   15    16   17   18
R4   19   20   21    22   23   24
R5   25   26   27    28   29   30